name: Build and deploy

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: 'package.json'

      - run: npm ci

      - run: npm run prod

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - uses: 'ramsey/composer-install@v3'

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: '.'
          target: '~/html/${{ inputs.domain }}'
          overwrite: true
