name: Deploy to test.aka-filmclub.de

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: test
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          pwd

      # - name: Copy files via SSH
      #   uses: appleboy/scp-action@v1
      #   with:
      #     host: ${{ secrets.SERVER_NAME }}
      #     port: ${{ secrets.SERVER_PORT }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     source: "build/"
      #     target: "/html/test.aka-filmclub.de"
