name: Run tests

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, synchronize]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'run-ci') || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run tests
        run: php artisan test
